name: prodt_test
description: A new Flutter project for test at prodt

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.16
  dio: ^4.0.6
  go_router: ^6.0.2
  intl: ^0.18.0
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  dio_cache_interceptor: ^3.3.1
  webview_flutter: ^4.0.2
  another_transformer_page_view: ^2.0.1
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/